# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb3fed10f8ff6b2668b2c3ed48011432b2320522b659956bc250f91b37e5d4d1a343c6b768b4d94e9bc400d850809c76871bbbd8f70bfd33be442483628920a

test:
  secret_key_base: 3434e4149c7aba72b2b4c9edb4f41977d4daed1eb958838fdc039013055e699d1ace4e429fb8d682e02f88bc7131460f6ee90335c8e40d725542507977baa2f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
